version: '3'
name: cloud

services:
  db:
    container_name: cloud-database.sesdata.local
    hostname: cloud-database.sesdata.local
    privileged: true
    image: mariadb:10.6
    restart: always
    ports:
      - 9001:3306
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=BpW8yOrbJc0NjIvi2GKcCFtyYVFagodIx4ljrBT5Jyn8u2LlLt
      - MYSQL_PASSWORD=BpW8yOrbJc0NjIvi2GKcCFtyYVFagodIx4ljrBT5Jyn8u2LlLt
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - cloud-network

  app:
    container_name: cloud.sesdata.local
    hostname: cloud.sesdata.local
    privileged: true
    image: nextcloud:fpm
    restart: always
    ports:
      - 9002:80
    links:
      - db
    volumes:
      - app:/var/www/html
    environment:
      - MYSQL_PASSWORD=BpW8yOrbJc0NjIvi2GKcCFtyYVFagodIx4ljrBT5Jyn8u2LlLt
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - cloud-network

volumes:
  db:
    name: cloud-database
  app:
    name: cloud-application

networks:
  cloud-network:
    name: cloud-network
    driver: bridge
